---
# tasks file for pr.moodle

- name: Moodle | needed tools
  apt: update-cache=yes force=yes state=present pkg={{ item }}
  sudo: yes
  with_items: pkg_dependencies

- name: Moodle | install python-pip
  apt: name=python-pip update_cache=yes state=latest
  sudo: yes

- name: Moodle | Update pip
  shell: pip install -U pip
  sudo: yes

- name: Moodle | Install modules for mysql management
  pip: name={{item}}
  sudo: yes
  with_items:
    - MySQL-python

- name: Moodle | Enable multiverse
  include: "ubuntu_enable_multiverse.yml"
  when: option_enable_multiverse == true

- name: Moodle | Install mysql
  include: "mysql.yml"
  when: option_install_mysql == true

- name: Moodle | Install APACHE
  include: "apache.yml"
  when: option_install_lamp == true

- name: Moodle | Install LAMP stack - select php family
  include: "php_apt_switchversion.yml"
  when: option_install_lamp == true

- name: Moodle | Install LAMP stack
  include: "php_apache.yml"
  when: option_install_lamp == true

- name: Moodle | Install additional php extensions
  include: "php_additional_extensions.yml"
  when: option_install_lamp == true and php_extensions is defined

- name: Moodle | Install moodle
  include: "moodle.yml"

- name: Moodle | Install moodle plugins
  include: "moodle_plugins.yml"
  when: moodle_plugins is defined

- name: Moodle | Enable incoming http(s) with ufw
  include: "ubuntu_configure_existing_ufw.yml"
  when: option_enable_ufw_http == true

