---
  - name: Moodle | Ensure multiverse repo is enabled
    apt_repository:
      repo: "{{item}}"
      update_cache: false
    register: multiverse_installed
    when: ansible_distribution == 'Ubuntu'
    sudo: yes
    with_items:
      - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
      - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
      - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
      - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

  - apt:
      update_cache: true
    when: multiverse_installed | changed
    sudo: yes

